kind: Service
apiVersion: v1
metadata:
  name: emqry
  namespace: ingress-nginx
  labels:
    k8s-app: emqry
spec:
  ports:
    - name: emqry
      protocol: TCP
      port: 60006
      targetPort: 60006
  selector:
    k8s-app: emqry
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
