kind: Service
apiVersion: v1
metadata:
  name: rabbit
  namespace: ingress-nginx
  labels:
    k8s-app: rabbit
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"rabbit"},"name":"rabbit","namespace":"ingress-nginx"},"spec":{"ports":[{"name":"rabbit","port":60046,"protocol":"TCP","targetPort":60046}],"selector":{"k8s-app":"rabbit"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
spec:
  ports:
    - name: rabbit
      protocol: TCP
      port: 60046
      targetPort: 60046
  selector:
    k8s-app: rabbit
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}