---
kind: Service
apiVersion: v1
metadata:
  name: redis-slave
  namespace: ingress-nginx
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave
    tier: backend
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
