apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv1 
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tmp 
    server: 10.1.7.141 
  persistentVolumeReclaimPolicy: Recycle 