kind: Deployment
apiVersion: apps/v1
metadata:
  name: bizpar
  namespace: ingress-nginx
  labels:
    k8s-app: bizpar
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: bizpar
  template:
    metadata:
      name: bizpar
      creationTimestamp: null
      labels:
        k8s-app: bizpar
    spec:
      containers:
        - name: bizpar
          image: 'leevy/hcis-bizpar:dev-281020-bag'
          env:
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-bizpar'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: REDIS_URL
              value: 'redis://:@redis-master:6379'
            - name: HYSTRIX_TIMEOUTINMS
              value: '60000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '60000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '180000'
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USERNAME
              value: user
            - name: RABBITMQ_PASSWORD
              value: 3tTtKhfISe
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
