kind: Deployment
apiVersion: apps/v1
metadata:
  name: cnbcmd
  namespace: ingress-nginx
  labels:
    k8s-app: cnbcmd
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cnbcmd
  template:
    metadata:
      name: cnbcmd
      creationTimestamp: null
      labels:
        k8s-app: cnbcmd
    spec:
      containers:
        - name: cnbcmd
          image: 'leevy/hcis-cnbcmd:STG-261020-BAG'
          env:
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-cnb'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: REDIS_URL
              value: 'redis://:@redis-master:6379'
            - name: BIZPAR_URL
              value: 'http://bizpar:60004/'
            - name: REPORT_URL
              value: 'http://report:60003/'
            - name: CFG_URL
              value: 'http://cfg:60032/'
            - name: ES_URL
              value: 'http://es:60002/'
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006/'
            - name: CNB_QRY_URL
              value: 'http://cnbqry:60010/'
            - name: LOAN_URL
              value: 'http://cnbqry:60010/'
            - name: TM_QRY_URL
              value: 'http://tmqry:60008/'
            - name: HYSTRIX_TIMEOUTINMS
              value: '600000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '600000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '1800000'
            - name: MINIO_URL
              value: 'http://minio:9000'
            - name: MINIO_ACCESS
              value: a3yGoaVcgH
            - name: MINIO_BUCKET
              value: dockerbucket
            - name: MINIO_SECRET
              value: lpkofre2Yjk50nFIqACTaVSawvl07U1DBn58sdZV
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USERNAME
              value: user
            - name: RABBITMQ_PASSWORD
              value: 3tTtKhfISe
            - name: MOVEMENT_QRY_URL
              value: 'http://mvqry:60017'
            - name: TERMINATION_QRY_URL
              value: 'http://tmnqry:60021'
            - name: BRMS_URL
              value: 'http://brms:60031'
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600