kind: Deployment
apiVersion: apps/v1
metadata:
  name: hcis-elasticsearch
  namespace: ingress-nginx
  labels:
    k8s-app: hcis-elasticsearch
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hcis-elasticsearch
  template:
    metadata:
      name: hcis-elasticsearch
      creationTimestamp: null
      labels:
        k8s-app: hcis-elasticsearch
    spec:
      containers:
        - name: hcis-elasticsearch
          image: 'leevy/hcis-elasticsearch:6e0f7ae'
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-master
            - name: ELASTICSEARCH_PORT
              value: '9200'
            - name: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
            - name: HYSTRIX_TIMEOUTINMS
              value: '600000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '600000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '1800000'
            - name: IDP_URL
              value: 'http://idp:60029'
            - name: ES_URL
              value: 'http://es:60002'
            - name: BIZPAR_URL
              value: 'http://bizpar:60004'
            - name: CFG_URL
              value: 'http://cfg:60032'
            - name: EM_QRY_URL
              value: 'http://emqry:60006'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
