kind: Deployment
apiVersion: apps/v1
metadata:
  name: idp
  namespace: ingress-nginx
  labels:
    k8s-app: idp
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: idp
  template:
    metadata:
      name: idp
      creationTimestamp: null
      labels:
        k8s-app: idp
    spec:
      containers:
        - name: idp
          image: 'leevy/hcis-idp:16d83bc'
          env:
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-idp'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: REDIS_URL
              value: 'redis://:@redis-master:6379'
            - name: HYSTRIX_TIMEOUTINMS
              value: '600000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '600000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '1800000'
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006'
            - name: ES_URL
              value: 'http://es:60002'
            - name: NOTIF_EMAIL_URL
              value: 'http://notification-emails:60049'
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 25
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-07-29T14:49:12Z'
      lastTransitionTime: '2019-12-24T23:30:14Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "idp-66d96dc5b8" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-10-22T11:02:37Z'
      lastTransitionTime: '2020-10-22T11:02:37Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
