kind: Deployment
apiVersion: apps/v1
metadata:
  name: maintenance
  namespace: ingress-nginx
  labels:
    k8s-app: maintenance
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: maintenance
  template:
    metadata:
      name: maintenance
      creationTimestamp: null
      labels:
        k8s-app: maintenance
    spec:
      containers:
        - name: maintenance
          image: 'fatir/maintenance:1.0.0'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
