kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbit
  namespace: ingress-nginx
  labels:
    k8s-app: rabbit
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rabbit
  template:
    metadata:
      name: rabbit
      creationTimestamp: null
      labels:
        k8s-app: rabbit
    spec:
      containers:
        - name: rabbit
          image: 'leevy/hcis-rabbit:261120-bag'
          env:
            - name: NOTIFICATION_FCM_URL
              value: 'http://notification-fcm:60040'
            - name: HCIS_ELASTICSEARCH_URL
              value: 'http://hcis-elasticsearch:60045'
            - name: RABBITMQ_HOST
              value: my-release-rabbitmq
            - name: RABBITMQ_USERNAME
              value: user
            - name: RABBITMQ_PASSWORD
              value: 2UIuTbitTV
            - name: MINIO_URL
              value: 'http://minio:9000'
            - name: MINIO_ACCESS
              value: a3yGoaVcgH
            - name: MINIO_BUCKET
              value: dockerbucket
            - name: MINIO_SECRET
              value: lpkofre2Yjk50nFIqACTaVSawvl07U1DBn58sdZV
            - name: TALENT_CMD_URL
              value: 'http://talentcmd:60041'
            - name: CNB_CMD_URL
              value: 'http://cnbcmd:60009'
            - name: CNB_QRY_URL
              value: 'http://cnbqry:60010'
            - name: EMP_QRY_URL
              value: 'http://emqry:60006'
            - name: CFG_URL
              value: 'http://cfg:60032'
            - name: REPORT_URL
              value: 'http://report:60003'
            - name: TM_URL
              value: 'http://tmcmd:60007'
            - name: MV_CMD_URL
              value: 'http://mvcmd:60016'
            - name: EM_CMD_URL
              value: 'http://emcmd:60005'
            - name: hcis.es.url
              value: 'http://es:60002'
            - name: hcis.configuration.url
              value: 'http://cfg:60032'
            - name: BRMS_URL
              value: 'http://brms:60031'
            - name: BLACKLIST_URL
              value: 'http://blacklist:60028'
            - name: TRN_CMD_URL
              value: 'http://trncmd:60022'
            - name: HCISREQUEST_URL
              value: 'http://requestcmd:60033'
            - name: ERECRUITMENT_URL
              value: 'http://erecruitment:60039'
            - name: MASTERDATA_URL
              value: 'http://masterdata:60001'
            - name: RECRUITMENT_CMD_URL
              value: 'http://recruitmentcmd:60013'
            - name: IDP_CMD_URL
              value: 'http://idp:60029'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 22
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-29T02:18:49Z'
      lastTransitionTime: '2020-11-29T02:18:49Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-29T02:18:54Z'
      lastTransitionTime: '2020-07-22T04:29:45Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "rabbit-6bc76d7bd" has successfully progressed.
