kind: Deployment
apiVersion: apps/v1
metadata:
  name: recruitmentqry
  namespace: ingress-nginx
  labels:
    k8s-app: recruitmentqry
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: recruitmentqry
  template:
    metadata:
      name: recruitmentqry
      creationTimestamp: null
      labels:
        k8s-app: recruitmentqry
    spec:
      containers:
        - name: recruitmentqry
          image: 'leevy/hcis-recruitmentqry:STG-221020-BAG'
          ports:
            - name: jvm-debug
              containerPort: 5005
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: >-
                -server -Xms10g -Xmx10g -XX:MaxDirectMemorySize=4096m
                -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewSize=3g
                -XX:MaxNewSize=3g -XX:+UseParNewGC -XX:MaxTenuringThreshold=2
                -XX:SurvivorRatio=8 -XX:+UnlockDiagnosticVMOptions
                -XX:ParGCCardsPerStrideChunk=32768 -XX:+UseConcMarkSweepGC
                -XX:CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled
                -XX:+CMSClassUnloadingEnabled 
                -XX:CMSInitiatingOccupancyFraction=80
                -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch
                -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
                -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution
                -XX:+PrintGCApplicationStoppedTime
                -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
            - name: JAVA_ENABLE_DEBUG
              value: 'false'
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-recruitment'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: REDIS_URL
              value: 'redis://:@redis-master:6379'
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006'
            - name: ES_URL
              value: 'http://es:60002'
            - name: CFG_URL
              value: 'http://cfg:60032'
            - name: BIZPAR_URL
              value: 'http://bizpar:60004'
            - name: MASTERDATA_URL
              value: 'http://masterdata:60001'
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006'
            - name: ES_URL
              value: 'http://es:60002'
            - name: CFG_URL
              value: 'http://cfg:60032'
            - name: HYSTRIX_TIMEOUTINMS
              value: '60000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '60000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '180000'
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
