kind: Deployment
apiVersion: apps/v1
metadata:
  name: report
  namespace: ingress-nginx
  labels:
    k8s-app: report
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: report
  template:
    metadata:
      name: report
      creationTimestamp: null
      labels:
        k8s-app: report
    spec:
      containers:
        - name: report
          image: 'leevy/hcis-report:dev-301020-bag'
          env:
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-report'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: REDIS_URL
              value: 'redis://:RQ6fNFvCHd@redis-master:6379'
            - name: EMPLOYEE_CMD_URL
              value: 'http://emcmd:60005'
            - name: ES_URL
              value: 'http://es:60002'
            - name: CNB_QRY_URL
              value: 'http://cnbqry:60010'
            - name: RECRUITMENT_CMD_URL
              value: 'http://recruitmentcmd:60013'
            - name: RECRUITMENT_QRY_URL
              value: 'http://recruitmentqry:60014'
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006'
            - name: CFG_URL
              value: 'http://cfg:60032'
            - name: BLACKLIST_URL
              value: 'http://blacklist:60028'
            - name: HCIS_ELASTICSEARCH_URL
              value: 'http://hcis-elasticsearch:60045'
            - name: TM_QRY_URL
              value: 'http://tmqry:60008'
            - name: MV_QRY_URL
              value: 'http://mvqry:60017'
            - name: TMN_QRY_URL
              value: 'http://tmnqry:60021'
            - name: REQUEST_QRY_URL
              value: 'http://requestqry:60034'
            - name: HYSTRIX_TIMEOUTINMS
              value: '600000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '600000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '1800000'
            - name: UPLOAD_PATH
              value: /home/
            - name: UNOCONV_PATH
              value: /usr/bin
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
