kind: Deployment
apiVersion: apps/v1
metadata:
  name: talentqry
  namespace: ingress-nginx
  labels:
    k8s-app: talentqry
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: talentqry
  template:
    metadata:
      name: talentqry
      creationTimestamp: null
      labels:
        k8s-app: talentqry
    spec:
      containers:
        - name: talentqry
          image: 'leevy/hcis-talentqry:c9572b8'
          env:
            - name: DB_USER
              value: hcis
            - name: DB_URL
              value: 'jdbc:postgresql://pg:5432/hcis-talent'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-do-pass
                  key: password
            - name: EMPLOYEE_QRY_URL
              value: 'http://emqry:60006/'
            - name: REDIS_URL
              value: 'redis://:@redis-master:6379'
            - name: HYSTRIX_TIMEOUTINMS
              value: '600000'
            - name: HYSTRIX_REQVOLUME_THRESHOLD
              value: '20'
            - name: HYSTRIX_SLEEPWINDOWINMS
              value: '600000'
            - name: HYSTRIX_ERRORTHRESHOLD
              value: '50'
            - name: HYSTRIX_TIMEINMS
              value: '1800000'
            - name: HIKARI_CONNECTION_TIMEOUT
              value: '20000'
            - name: HIKARI_MIN_IDLE
              value: '10'
            - name: HIKARI_MAXPOOL_SIZE
              value: '20'
            - name: HIKARI_IDLE_TIMEOUT
              value: '100000'
            - name: HIKARI_MAX_LIFETIME
              value: '1000'
            - name: HIKARI_MAX_AUTOCOMMIT
              value: 'true'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.0.0.2
          hostnames:
            - pg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600