kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-sls-erecruitment
  namespace: ingress-nginx
  labels:
    k8s-app: web-sls-erecruitment
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: web-sls-erecruitment
  template:
    metadata:
      name: web-sls-erecruitment
      creationTimestamp: null
      labels:
        k8s-app: web-sls-erecruitment
    spec:
      containers:
        - name: web-sls-erecruitment
          image: 'leevy/hcis-erec-ui-boot:stg-300920'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600